package net.auto.async.processor;

import com.google.auto.service.AutoService;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableSet;
import com.squareup.javapoet.*;
import net.auto.async.AutoGenerated;

import javax.annotation.processing.Processor;
import javax.annotation.processing.RoundEnvironment;
import javax.lang.model.element.*;
import javax.lang.model.util.ElementFilter;
import java.lang.annotation.Annotation;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Set;

@AutoService(Processor.class)
public class AutoGeneratedProcessor extends AnnotationProcessorSupport {

    @Override
    public Set<String> getSupportedAnnotationTypes() {
        return ImmutableSet.of(AutoGenerated.class.getName());
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        Collection<? extends Element> annotatedElements = roundEnv.getElementsAnnotatedWith(AutoGenerated.class);
        List<TypeElement> types = new ImmutableList.Builder<TypeElement>()
                .addAll(ElementFilter.typesIn(annotatedElements))
                .build();
        for (final TypeElement typeElement : types) {
            AutoGenerated autoGenerated = typeElement.getAnnotation(AutoGenerated.class);
            if (!autoGenerated.value().equals("net.auto.async.processor.AutoAsyncProcessor") ||
                    !autoGenerated.generateFacade()) {
                continue;
            }
            try {

                List<MethodSpec> methodSpecs = new ArrayList<MethodSpec>();
                for (Element enclosed : typeElement.getEnclosedElements()) {
                    if (enclosed.getKind() == ElementKind.METHOD) {
                        ExecutableElement executableElement = (ExecutableElement) enclosed;
                        methodSpecs.add(processExecutableElement(executableElement));
                    }
                }
                TypeSpec facade = TypeSpec.classBuilder("Facade_" + getSimpleTypeName(typeElement))
                        .addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)
                        .addSuperinterface(TypeName.get(typeElement.asType()))
                        .addMethods(methodSpecs)
                        .addAnnotation(AnnotationSpec.get(new AutoGenerated() {

                            @Override
                            public Class<? extends Annotation> annotationType() {
                                return AutoGenerated.class;
                            }

                            @Override
                            public String value() {
                                return "net.auto.async.processor.AutoGeneratedProcessor";
                            }

                            @Override
                            public boolean generateFacade() {
                                return false;
                            }
                        }))
                        .build();

                generateJavaFile(getPackageName(typeElement), facade);
            } catch (Exception e) {
                reportError(typeElement, "Create javaFile failed cause @%s ", e.getMessage());
                return true;
            }
        }
        return false;
    }

    protected MethodSpec processExecutableElement(ExecutableElement executableElement) {
        List<ParameterSpec> parameterSpecs = new ArrayList<ParameterSpec>();
        for (Element element : executableElement.getParameters()) {
            ParameterSpec parameterSpec = processVariableElement((VariableElement) element);
            parameterSpecs.add(parameterSpec);
        }
        TypeName returnTypeName = TypeName.get(executableElement.getReturnType());
        return MethodSpec
                .methodBuilder(executableElement.getSimpleName().toString())
                .addModifiers(Modifier.PUBLIC)
                .returns(returnTypeName)
                .addParameters(parameterSpecs)
                .addStatement("return null")
                .build();
    }


}
